name: Litter
options:
  bundleIdPrefix: com.litter
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true


settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: targeted
    SWIFT_OBJC_BRIDGING_HEADER: Sources/Litter/Bridge/codex_bridge_objc.h
    OTHER_LDFLAGS: "$(inherited) -lc++ -lz"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"

packages:
  Citadel:
    url: https://github.com/orlandos-nl/Citadel
    from: "0.8.0"
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
  Inject:
    url: https://github.com/krzysztofzablocki/Inject
    from: "1.5.2"

targets:
  LitterRemote:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Litter
        excludes:
          - "**/*.h"
    dependencies:
      - sdk: Security.framework
      - sdk: SystemConfiguration.framework
      - sdk: Network.framework
      - package: Citadel
      - package: MarkdownUI
      - package: Inject
      - framework: Frameworks/ios_system/ios_system.xcframework
        embed: true
      - framework: Frameworks/ios_system/shell.xcframework
        embed: true
      - framework: Frameworks/ios_system/text.xcframework
        embed: true
      - framework: Frameworks/ios_system/files.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.litter.app.remote
        INFOPLIST_FILE: Sources/Litter/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Litter/Bridge/codex_bridge_objc.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) LITTER_DISABLE_ON_DEVICE_CODEX"
      configs:
        Debug:
          OTHER_LDFLAGS: "$(inherited) -lc++ -lz"
  Litter:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Litter
        excludes:
          - "**/*.h"
    dependencies:
      - framework: Frameworks/codex_bridge.xcframework
        embed: true
      - sdk: Security.framework
      - sdk: SystemConfiguration.framework
      - sdk: Network.framework
      - package: Citadel
      - package: MarkdownUI
      - package: Inject
      - framework: Frameworks/ios_system/ios_system.xcframework
        embed: true
      - framework: Frameworks/ios_system/shell.xcframework
        embed: true
      - framework: Frameworks/ios_system/text.xcframework
        embed: true
      - framework: Frameworks/ios_system/files.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.litter.app
        INFOPLIST_FILE: Sources/Litter/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Litter/Bridge/codex_bridge_objc.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          OTHER_LDFLAGS: "$(inherited) -lc++ -lz"

schemes:
  LitterRemote:
    build:
      targets:
        LitterRemote: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
    management:
      isShown: true
      orderHint: 0
  Litter:
    build:
      targets:
        Litter: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
    management:
      isShown: true
      orderHint: 1
