name: Litter
options:
  bundleIdPrefix: com.litter
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true


settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: targeted
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_OBJC_BRIDGING_HEADER: Sources/Litter/Bridge/codex_bridge_objc.h
    OTHER_LDFLAGS: "$(inherited) -lc++ -lz"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"

packages:
  Citadel:
    url: https://github.com/orlandos-nl/Citadel
    from: "0.8.0"
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
  Inject:
    url: https://github.com/krzysztofzablocki/Inject
    from: "1.5.2"
  Highlightr:
    url: https://github.com/raspu/Highlightr
    from: "2.1.0"

targets:
  LitterRemote:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Litter
        excludes:
          - "**/*.h"
    resources:
      - path: Sources/Litter/Resources/ios_system/commandDictionary.plist
      - path: Sources/Litter/Resources/ios_system/extraCommandsDictionary.plist
      - path: Sources/Litter/Resources/Fonts
    dependencies:
      - sdk: Security.framework
      - sdk: SystemConfiguration.framework
      - sdk: Network.framework
      - package: Citadel
      - package: MarkdownUI
      - package: Inject
      - package: Highlightr
      - framework: Frameworks/ios_system/ios_system.xcframework
        embed: true
      - framework: Frameworks/ios_system/shell.xcframework
        embed: true
      - framework: Frameworks/ios_system/text.xcframework
        embed: true
      - framework: Frameworks/ios_system/files.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sigkitten.litter.remote
        INFOPLIST_FILE: Sources/Litter/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Litter/Bridge/codex_bridge_objc.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) LITTER_DISABLE_ON_DEVICE_CODEX"
      configs:
        Debug:
          OTHER_LDFLAGS: "$(inherited) -lc++ -lz"
  Litter:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Litter
        excludes:
          - "**/*.h"
    resources:
      - path: Sources/Litter/Resources/ios_system/commandDictionary.plist
      - path: Sources/Litter/Resources/ios_system/extraCommandsDictionary.plist
      - path: Sources/Litter/Resources/Fonts
    dependencies:
      - framework: Frameworks/codex_bridge.xcframework
        embed: false
      - sdk: Security.framework
      - sdk: SystemConfiguration.framework
      - sdk: Network.framework
      - package: Citadel
      - package: MarkdownUI
      - package: Inject
      - package: Highlightr
      - framework: Frameworks/ios_system/ios_system.xcframework
        embed: true
      - framework: Frameworks/ios_system/shell.xcframework
        embed: true
      - framework: Frameworks/ios_system/text.xcframework
        embed: true
      - framework: Frameworks/ios_system/files.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sigkitten.litter
        INFOPLIST_FILE: Sources/Litter/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Litter/Bridge/codex_bridge_objc.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          OTHER_LDFLAGS: "$(inherited) -lc++ -lz"
  CodexIOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Tests/CodexIOSTests
    dependencies:
      - target: Litter
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: false
        CODE_SIGNING_REQUIRED: false

schemes:
  LitterRemote:
    build:
      targets:
        LitterRemote: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
    management:
      isShown: true
      orderHint: 0
  Litter:
    build:
      targets:
        Litter: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CodexIOSTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
    management:
      isShown: true
      orderHint: 1
